import proccuctImg from '../../../../../assets/img/productImg.png';

const SpiringData = [
  {
    id: 4,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 10,
    pPrice: 590.0,
    pDiscount: 80,
    totalStock: 15,
    soldQuantity: 14,
  },
  {
    id: 5,
    img: proccuctImg,
    name: 'AUDIO',
    pName: `ndustry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 50,
    totalStock: 100,
    soldQuantity: 70,
  },
  {
    id: 6,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 20,
    totalStock: 105000,
    soldQuantity: 40000,
  },
  {
    id: 7,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 30,
    totalStock: 10205,
    soldQuantity: 4000,
  },
  {
    id: 8,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 40,
    totalStock: 1000005,
    soldQuantity: 40000,
  },
];

export default SpiringData;
