import proccuctImg from '../../../../assets/img/productImg.png';
export const featuredProductApi = [
  {
    id: 1,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 159.0,
    pDiscount: 10,
  },
  {
    id: 2,
    img: proccuctImg,
    name: 'LAPTOP',
    pName:
      'S21 Laptop Ultra HD LED Screen Feature 2023 ... S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...S21 Laptop Ultra HD LED Screen Feature 2023 ...',
    ratings: 4.5,
    ratingsCount: 10,
    pPrice: 59.0,
    pDiscount: 20,
  },
  {
    id: 3,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 3.5,
    ratingsCount: 20,
    pPrice: 59.0,
    pDiscount: 30,
  },
  {
    id: 4,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 10,
    pPrice: 590.0,
    // pDiscount: 10,
  },
  {
    id: 5,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 6,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 7,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 8,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 9,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 10,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 11,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 12,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 13,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 14,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 15,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 16,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 17,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 18,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 19,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 20,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 21,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 22,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 23,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 24,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 25,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 26,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 27,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 28,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 29,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
  {
    id: 30,
    img: proccuctImg,
    name: 'AUDIO',
    pName: 'WH-1000XM4 Wireless Headphones High Qu...',
    ratings: 2.5,
    ratingsCount: 120,
    pPrice: 59.0,
    pDiscount: 10,
  },
];
