import proccuctImg from '../../../../assets/img/productImg.png';
export const featuredProductApi = [
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 1,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 1',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 2,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 2',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 3,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 3',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 4,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 4',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 5,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 5',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 6,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 6',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 7,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 7',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 8,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 8',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 9,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 9',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 10,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 10',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 11,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 11',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 12,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 12',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 13,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 13',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 14,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 14',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 15,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 15',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 16,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 16',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 17,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 17',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 18,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 18',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 19,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 19',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 20,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 20',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 21,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 21',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 22,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 22',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 23,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 23',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 24,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 24',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 25,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 25',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 26,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 26',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 27,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 27',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 28,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 28',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 29,
    image: 'https://picsum.photos/200/200?random=29',
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 29',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
  {
    brand: 'Samsung',
    delivery: '2-3 business days',
    discount: 20,
    id: 30,
    image: proccuctImg,
    pCategory: 'Phone',
    pName: 'iPhone 14 Pro Max - 30',
    price: 237.1,
    ratings: 4.5,
    size: '13.3 inches',
    totalRatings: 213,
    variant: ['black', 'green', 'silver'],
    weight: '1.5kg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  },
];
